- name: Reading unseal key contents
  command: cat {{item}}
  register: unseal_keys
  with_fileglob: "{{ unseal_keys_dir_output }}/*"
  delegate_to: localhost
  become: no

- name: Unseal vault with unseal keys
  shell: |
    vault operator unseal {{ item.stdout }}
  with_items: "{{unseal_keys.results}}"

- name: Daemon systemd_reload
  become: yes
  become_user: root
  become_method: sudo
  command: sudo systemctl daemon-reload

- name: Vault welcome note
  command: echo "************ WELCOME to HASHICORP VAULT ***************"
  register: welcome_vault

- debug: msg="{{ welcome_vault }}"