- name: Reading unseal key contents
  command: cat {{item}}
  register: unseal_keys
  with_fileglob: "{{ unseal_keys_dir_output }}/*"
  delegate_to: localhost
  become: no

- name: Vault UNSEALING note
  shell: echo "************ UNSEALING VAULT IN-PROGRESS ***************"
  register: unseal_vault
 
- debug: msg="{{ unseal_vault }}"
- pause:
      seconds: 15

- name: Unseal vault with unseal keys
  shell: |
    vault operator unseal {{ item.stdout }}
  with_items: "{{unseal_keys.results}}"

- pause:
      seconds: 10

- name: Vault welcome note if its active
  ansible.builtin.command: echo "************ WELCOME to HASHICORP VAULT ***************"
  when: vault.status="active"
  register: welcome_vault
  tag: vaultstatus
 
- debug: msg="{{ welcome_vault }}"

- name: Daemon systemd_reload, verify the vault.service is up and running.
  become: yes
  become_user: root
  become_method: sudo
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: vault.service