- name: Reload systemd
  command: systemctl daemon-reload
  listen: "systemd_reload"

- name: Restart vault.service
  service:
      name: vault.service
      state: restarted
  listen: "restart vault.service"